-- PARTIAL WEEK 적용 후 MONTHLY 로 보기

WITH SA AS (
		SELECT BASE_DATE + 0	AS FROM_DATE
		     , COALESCE(LEAD(BASE_DATE+0,1) OVER (PARTITION BY IH.LVL05_CD, AH.LVL03_CD ORDER BY BASE_DATE ASC)-1, TO_DATE('2023-04-24', 'YYYY-MM-DD'))	AS TO_DATE
			 , IH.LVL05_CD AS ITEM_CD
			 , AH.LVL03_CD AS ACCOUNT_CD
			 , QTY 
	      FROM TB_CM_ACTUAL_SALES SA
		 INNER JOIN TB_DPD_ITEM_HIERACHY2 IH ON SA.ITEM_MST_ID = IH.LVL05_ID
		 INNER JOIN TB_DPD_ACCOUNT_HIERACHY2 AH ON SA.ACCOUNT_ID = AH.LVL03_ID
		 WHERE IH.LVL05_CD = '68313' AND AH.LVL03_CD = '01_POS'
	) 
	, CAL AS (
	    SELECT MIN(DAT)				AS FROM_DATE
			 , MAX(DAT)				AS TO_DATE
			 , MIN(YYYYMM)			AS YYYYMM
			 , COUNT(DAT)			AS DAT_CNT
		  FROM TB_CM_CALENDAR	
	     WHERE DAT BETWEEN '2019-12-30' AND '2023-04-24' 
	  GROUP BY YYYY
			 , MM
			 , TO_CHAR(DP_WK)
	) 
	, PW_SA AS (
		SELECT CAL.FROM_DATE AS BASE_DATE
			 , CAL.YYYYMM
			 , ITEM_CD
			 , ACCOUNT_CD
		 	 , ROUND(SA.QTY * CAL.DAT_CNT / (SA.TO_DATE-SA.FROM_DATE+1))  AS QTY
	 	  FROM SA 
		 RIGHT JOIN CAL ON CAL.FROM_DATE BETWEEN SA.FROM_DATE AND SA.TO_DATE
	)
	, M_SA AS (
		SELECT MIN(BASE_DATE) AS BASE_DATE
		 	 , ITEM_CD
		 	 , ACCOUNT_CD
		 	 , SUM(QTY) AS QTY 
		  FROM PW_SA 
		 GROUP BY YYYYMM, ITEM_CD, ACCOUNT_CD
	) SELECT * FROM M_SA ORDER BY 1;