CREATE OR REPLACE procedure DWSCM_DEV."SP_UI_BF_00_MAKE_FACTOR" 
(
	p_FACTOR_NM 		VARCHAR2,
	p_FACTOR_DESC		VARCHAR2,
	p_FROM_DATE	 		DATE,
	p_TO_DATE			DATE,
	p_APPLY_FROM_DATE	DATE,
	p_APPLY_TO_DATE		DATE,
	pRESULT				OUT SYS_REFCURSOR
)
IS 
	p_FACTOR_CD			VARCHAR2(100);
	v_sql				VARCHAR2(32767);
BEGIN
	BEGIN
		SELECT 'FACTOR'||LPAD(SUBSTR(FACTOR_CD, 7) + 1, 2, '0') INTO p_FACTOR_CD
		  FROM (SELECT FACTOR_CD 
		 		  FROM TB_BF_FACTOR_MGMT
				 WHERE FACTOR_CD LIKE 'FACTOR%' AND ROWNUM = 1
				 ORDER BY 1 DESC);
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				p_FACTOR_CD := 'FACTOR01';
	END;

	EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_DATE_FACTOR2';

	v_sql := ' INSERT INTO TB_BF_FACTOR_MGMT (
				  FACTOR_CD 
			    , COL_NM 
				, DESCRIP
				, EXTEND_YN
				, CREATE_BY
				, CREATE_DTTM
				, MODIFY_BY
				, MODIFY_DTTM
				, ACTV_YN
				, DEL_YN
				) 
				SELECT ''' || p_FACTOR_CD || ''' AS FACTOR_CD
				     , ''' || p_FACTOR_NM || ''' AS COL_NM
					 , ''' || p_FACTOR_DESC || ''' AS DESCRIP
					 , ''N'' AS EXTEND_YN
					 , ''admin'' AS CREATE_BY
					 , SYSDATE AS CREATE_DTTM
					 , NULL AS MODIFY_BY
					 , NULL AS MODIFY_DTTM
					 , ''N'' AS ACTV_YN
					 , ''N'' AS DEL_YN
				FROM DUAL';
		EXECUTE IMMEDIATE v_sql;
	
	v_sql := 'INSERT INTO TEMP_DATE_FACTOR2 (
					ID, 
					BASE_DATE,	
					' || p_FACTOR_CD || '
				 )
				 WITH MMDD AS (
					SELECT DISTINCT SUBSTR(DAT_ID, 5) AS DAT_ID
					  FROM TB_CM_CALENDAR 
					 WHERE DAT BETWEEN ''' || p_FROM_DATE || ''' AND ''' || p_TO_DATE || '''
				 ), 
				 FCT AS (
					SELECT CA.DAT
						 , 1 AS ' || p_FACTOR_CD || ' 
					  FROM TB_CM_CALENDAR CA 
					 INNER JOIN MMDD ON SUBSTR(CA.DAT_ID, 5) = MMDD.DAT_ID
				 ),
				 NEW_FCT AS (
					SELECT RAWTOHEX(SYS_GUID()) AS ID
						 , CA.DAT AS BASE_DATE
						 , CASE WHEN FCT.' || p_FACTOR_CD || ' IS NULL THEN 0 ELSE FCT.' || p_FACTOR_CD || ' END AS ' || p_FACTOR_CD || '
					  FROM TB_CM_CALENDAR CA
					  LEFT JOIN FCT ON CA.DAT = FCT.DAT
				     WHERE CA.DAT BETWEEN ''' || p_APPLY_FROM_DATE || ''' AND ''' || p_APPLY_TO_DATE || '''
					 ORDER BY 1
				 ) SELECT * FROM NEW_FCT';
				
		EXECUTE IMMEDIATE v_sql;
						 
		v_sql := 'UPDATE TB_BF_DATE_FACTOR DF
				 SET DF.' || p_FACTOR_CD || ' = (SELECT ' || p_FACTOR_CD || '
												   FROM TEMP_DATE_FACTOR2 DF2 
												  WHERE DF.BASE_DATE = DF2.BASE_DATE)';
		EXECUTE IMMEDIATE v_sql;		

	OPEN pRESULT FOR 'SELECT * FROM TB_BF_FACTOR_MGMT';
END;