CREATE OR REPLACE PROCEDURE DWSCM_DEV."SP_UI_BF_00_SEASONAL_INDEX" 
(
	p_VER_CD 		VARCHAR2,
	p_ITEM_CD 		VARCHAR2,
	p_ACCOUNT_CD 	VARCHAR2,
	pRESULT		OUT SYS_REFCURSOR
)
IS
	p_TARGET_FROM_DATE 	DATE;
	p_TARGET_TO_DATE 	DATE;

BEGIN
	SELECT MAX(TARGET_FROM_DATE)
		 , MAX(TARGET_TO_DATE)
		 INTO
		   p_TARGET_FROM_DATE
		 , p_TARGET_TO_DATE
	  FROM TB_BF_CONTROL_BOARD_VER_DTL
	WHERE VER_CD = p_VER_CD;

	OPEN pRESULT FOR 
	WITH CAL AS (
		SELECT MIN(DAT)				AS FROM_DATE
			 , MAX(DAT)				AS TO_DATE
			 , MIN(YYYYMM)			AS YYYYMM
			 , COUNT(DAT)			AS DAT_CNT
		  FROM TB_CM_CALENDAR	
	     WHERE DAT BETWEEN p_TARGET_FROM_DATE AND p_TARGET_TO_DATE
	  GROUP BY YYYY, MM, TO_CHAR(DP_WK)
	)
	, RT AS (
		SELECT BASE_DATE + 0	AS FROM_DATE
		     , COALESCE(LEAD(BASE_DATE+0,1) OVER (PARTITION BY ITEM_CD, ACCOUNT_CD ORDER BY BASE_DATE ASC)-1, p_TARGET_TO_DATE)	AS TO_DATE
			 , ITEM_CD
			 , ACCOUNT_CD
			 , QTY
		  FROM TB_BF_RT_FINAL RT
		 WHERE VER_CD = p_VER_CD AND ITEM_CD = p_ITEM_CD AND ACCOUNT_CD = p_ACCOUNT_CD
	)
	, PW_RT AS (
		SELECT CAL.FROM_DATE AS BASE_DATE
			 , CAL.YYYYMM
			 , ITEM_CD
			 , ACCOUNT_CD
		 	 , ROUND(RT.QTY * CAL.DAT_CNT / (RT.TO_DATE-RT.FROM_DATE+1))  AS QTY
	 	  FROM RT 
		 RIGHT JOIN CAL ON CAL.FROM_DATE BETWEEN RT.FROM_DATE AND RT.TO_DATE
	) 
	, AVG_RT AS (
		SELECT YYYYMM
		     , ITEM_CD
		     , ACCOUNT_CD
		     , AVG(QTY) AS QTY 
		  FROM PW_RT 
		 GROUP BY YYYYMM, ITEM_CD, ACCOUNT_CD	
	)	
	, SUM_RT AS (
		SELECT SUM(QTY) AS SUM_QTY
		  FROM AVG_RT
	)
	, SES AS (
		SELECT ITEM_CD
			 , ACCOUNT_CD
			 , YYYYMM AS MONTH
			 , 100 * QTY / SUM_QTY AS SEASONAL_IDX
		  FROM AVG_RT 
		 CROSS JOIN SUM_RT
	) SELECT * FROM SES ORDER BY 3;
END;