CREATE OR REPLACE PROCEDURE DWSCM_DEV."SP_UI_BF_00_SEASONAL_INDEX" 
(
	p_VER_CD 		VARCHAR2,
	p_ITEM_CD 		VARCHAR2,
	p_ACCOUNT_CD 	VARCHAR2,
	pRESULT		OUT SYS_REFCURSOR
)
IS
	p_INPUT_FROM_DATE 	DATE;
	p_INPUT_TO_DATE 	DATE;
	p_TARGET_FROM_DATE 	DATE;
	p_TARGET_TO_DATE 	DATE;

BEGIN
	SELECT DISTINCT INPUT_FROM_DATE
		 , INPUT_TO_DATE
		 , TARGET_FROM_DATE
		 , TARGET_TO_DATE 
		 INTO
		   p_INPUT_FROM_DATE
		 , p_INPUT_TO_DATE
		 , p_TARGET_FROM_DATE
		 , p_TARGET_TO_DATE
	  FROM TB_BF_CONTROL_BOARD_VER_DTL tbcbvd
	WHERE VER_CD = p_VER_CD 
	  AND INPUT_FROM_DATE IS NOT NULL;

	OPEN pRESULT FOR 
	WITH SA AS (
		SELECT AVG(QTY) AS AVG_QTY 
		  FROM (
			SELECT SUBSTR(CAL.DP_WK, 5) AS WEEK
				 , IH.LVL05_CD AS ITEM_CD
				 , AH.LVL03_CD AS ACCOUNT_CD 
				 , AVG(QTY) AS QTY
			  FROM TB_CM_ACTUAL_SALES SA
			 INNER JOIN TB_DPD_ITEM_HIERACHY2 IH ON SA.ITEM_MST_ID = IH.LVL05_ID
		 	 INNER JOIN TB_DPD_ACCOUNT_HIERACHY2 AH ON SA.ACCOUNT_ID = AH.LVL03_ID
		 	 INNER JOIN TB_CM_CALENDAR CAL ON SA.BASE_DATE = CAL.DAT
			 WHERE IH.LVL05_CD = p_ITEM_CD 
			   AND AH.LVL03_CD = p_ACCOUNT_CD 
			   AND BASE_DATE BETWEEN p_INPUT_FROM_DATE AND p_INPUT_TO_DATE
			 GROUP BY SUBSTR(CAL.DP_WK, 5), IH.LVL05_CD, AH.LVL03_CD
			 )
		)
	, RT AS (
		SELECT ITEM_CD
			 , ACCOUNT_CD
			 , RT.BASE_DATE
			 , SUBSTR(CAL.DP_WK, 5) AS WEEK
			 , AVG(QTY) AS QTY
		  FROM TB_BF_RT_FINAL RT
		 INNER JOIN TB_CM_CALENDAR CAL ON RT.BASE_DATE = CAL.DAT
		 WHERE VER_CD = p_VER_CD AND ITEM_CD = p_ITEM_CD AND ACCOUNT_CD = p_ACCOUNT_CD
		 GROUP BY SUBSTR(CAL.DP_WK, 5), ITEM_CD, ACCOUNT_CD, RT.BASE_DATE
		) 
	, CAL AS (
		SELECT ITEM_CD
			 , ACCOUNT_CD
			 , WEEK
			 , BASE_DATE
			 , ((QTY - AVG_QTY) / AVG_QTY) * 100 AS SEASONAL_IDX
		  FROM RT 
		 CROSS JOIN SA
		) 
		SELECT ITEM_CD
			 , ACCOUNT_CD
	 		 , WEEK
			 , SEASONAL_IDX
	      FROM CAL
	     ORDER BY BASE_DATE;
END;