CREATE OR REPLACE PROCEDURE DWSCM.SP_UI_BF_67_Q1 (
	 p_VER_CD VARCHAR2
   , p_FROM_DATE DATE
   , p_TO_DATE DATE
   , pRESULT OUT SYS_REFCURSOR
   )
IS
  /**************************************************************************
   * Copyrightⓒ2023 ZIONEX, All rights reserved.
   **************************************************************************
   * Name : SP_UI_BF_67_Q1
   * Purpose : 수요예측 버전 이력 관리 조회
   * Notes :
   **************************************************************************/
/**
DECLARE
	pRESULT SYS_REFCURSOR;
BEGIN
	DWSCM.SP_UI_BF_67_Q1('BF-20230911-01', '2023-08-01', '2023-09-12', pRESULT);
	DWSCM.SP_UI_BF_67_Q1('', '2023-08-01', '2023-09-13', pRESULT);
	DBMS_SQL.RETURN_RESULT(pRESULT);
END; 
**/
   v_VER_CD VARCHAR2(100);
   v_FROM_DATE DATE;
   v_TO_DATE DATE;
   BEGIN
	   v_VER_CD := NVL(p_VER_CD ,'');
	   v_FROM_DATE := NVL(p_FROM_DATE, TRUNC(SYSDATE - 35, 'IW'));
	   v_TO_DATE := NVL(p_TO_DATE, SYSDATE);
	    IF p_VER_CD IS NULL
   		THEN 
   		OPEN pRESULT FOR
   			SELECT VER_CD
				 , TO_DATE(SUBSTR(VER_CD, 4, 8), 'YYYY-MM-DD') AS BASE_DATE
				 , STATUS
				 , LISTAGG(NVL(ENGINE_TP_CD,DESCRIP), ',') WITHIN GROUP(ORDER BY PROCESS_NO) AS PROCESS
			     , RUN_STRT_DATE
			     , RUN_END_DATE
			     , MAX(RULE_01) AS RULE_01
			 	 , MAX(VAL_TP) AS VAL_TP
		 		 , MAX(INPUT_BUKT_CD) AS INPUT_BUKT_CD
				 , MAX(TARGET_BUKT_CD) AS TARGET_BUKT_CD
				 , MAX(ITEM_LV_CD) AS ITEM_LV_CD
			 	 , MAX(SALES_LV_CD) AS SALES_LV_CD
				 , MAX(INPUT_FROM_DATE) AS INPUT_FROM_DATE
				 , MAX(INPUT_TO_DATE) AS INPUT_TO_DATE
				 , MAX(TARGET_FROM_DATE) AS TARGET_FROM_DATE
				 , MAX(TARGET_TO_DATE) AS TARGET_TO_DATE
				 , C.LV_NM AS ITEM_LV_NM
				 , D.LV_NM AS SALES_LV_NM
			  FROM TB_BF_CONTROL_BOARD_VER_DTL B
			  LEFT JOIN TB_CM_LEVEL_MGMT C
		        ON B.ITEM_LV_CD = C.LV_CD 
		       AND C.LV_TP_ID = (SELECT ID FROM TB_CM_COMM_CONFIG WHERE CONF_CD = 'I' AND CONF_GRP_CD = 'DP_LV_TP')
		      LEFT JOIN TB_CM_LEVEL_MGMT D
		        ON B.SALES_LV_CD = D.LV_CD
		       AND D.LV_TP_ID = (SELECT ID FROM TB_CM_COMM_CONFIG WHERE CONF_CD = 'S' AND CONF_GRP_CD = 'DP_LV_TP')
		     WHERE VER_CD LIKE 'BF-%'
			   AND RUN_STRT_DATE BETWEEN v_FROM_DATE AND v_TO_DATE
			   AND VER_CD IN (SELECT VER_CD FROM TB_BF_CONTROL_BOARD_VER_DTL WHERE PROCESS_NO = 1000000 AND STATUS = 'Completed')
		     GROUP BY VER_CD, STATUS, RUN_STRT_DATE, RUN_END_DATE, C.LV_NM, D.LV_NM
		     ORDER BY BASE_DATE DESC, RUN_STRT_DATE;
   		ELSE
   		OPEN pRESULT FOR
   			SELECT VER_CD
				 , TO_DATE(SUBSTR(VER_CD, 4, 8), 'YYYY-MM-DD') AS BASE_DATE
				 , STATUS
				 , LISTAGG(NVL(ENGINE_TP_CD,DESCRIP), ',') WITHIN GROUP(ORDER BY PROCESS_NO) AS PROCESS
			     , RUN_STRT_DATE
			     , RUN_END_DATE
			     , MAX(RULE_01) AS RULE_01
			 	 , MAX(VAL_TP) AS VAL_TP
		 		 , MAX(INPUT_BUKT_CD) AS INPUT_BUKT_CD
				 , MAX(TARGET_BUKT_CD) AS TARGET_BUKT_CD
				 , MAX(ITEM_LV_CD) AS ITEM_LV_CD
			 	 , MAX(SALES_LV_CD) AS SALES_LV_CD
				 , MAX(INPUT_FROM_DATE) AS INPUT_FROM_DATE
				 , MAX(INPUT_TO_DATE) AS INPUT_TO_DATE
				 , MAX(TARGET_FROM_DATE) AS TARGET_FROM_DATE
				 , MAX(TARGET_TO_DATE) AS TARGET_TO_DATE
				 , C.LV_NM AS ITEM_LV_NM
				 , D.LV_NM AS SALES_LV_NM
			  FROM TB_BF_CONTROL_BOARD_VER_DTL B
			  LEFT JOIN TB_CM_LEVEL_MGMT C
		        ON B.ITEM_LV_CD = C.LV_CD 
		       AND C.LV_TP_ID = (SELECT ID FROM TB_CM_COMM_CONFIG WHERE CONF_CD = 'I' AND CONF_GRP_CD = 'DP_LV_TP')
		      LEFT JOIN TB_CM_LEVEL_MGMT D
		        ON B.SALES_LV_CD = D.LV_CD
		       AND D.LV_TP_ID = (SELECT ID FROM TB_CM_COMM_CONFIG WHERE CONF_CD = 'S' AND CONF_GRP_CD = 'DP_LV_TP')
			 WHERE VER_CD LIKE 'BF-%'
			   AND VER_CD = v_VER_CD
--			   AND RUN_STRT_DATE BETWEEN v_FROM_DATE AND v_TO_DATE
			 GROUP BY VER_CD, STATUS, RUN_STRT_DATE, RUN_END_DATE, C.LV_NM, D.LV_NM
			 ORDER BY BASE_DATE DESC, RUN_STRT_DATE;
	   	END IF;
   END;